version: '3'
services:
  jupyterlab:
    build: .
    image: jupyterlab-test-img
    container_name: jupyterlab-test
    working_dir: /home
    volumes:
      - .:/home/Pokemon-SV
      - D:\PROJECT\201_HaMaruki\201_60_PokemonSV\Pokemon-SV-Datasets:/home/Pokemon-SV-Datasets
    ports:
      - "8888:8888"
    command:
      jupyter-lab --ip 0.0.0.0 --allow-root -b localhost